# Generated by Django 5.0.2 on 2025-06-30 12:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkitem',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='checkitem',
            name='verifie_par',
            field=models.CharField(blank=True, max_length=200, verbose_name='Vérifié par'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='description',
            field=models.TextField(blank=True, help_text="Aide (affiché dans l'infobulle) pour cette tâche."),
        ),
        migrations.CreateModel(
            name='DocLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Texte du lien (ex. 'Réseau')", max_length=100)),
                ('url', models.URLField(help_text='URL de la doc')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_links', to='checklist.tasktemplate')),
            ],
            options={
                'ordering': ['ordre', 'label'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCheckItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('A_VERIFIER', '🔍 À vérifier'), ('OK', '✅ OK'), ('KO', '❌ KO'), ('EN_COURS', '🔄 En cours')], default='A_VERIFIER', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('verifie_par', models.CharField(blank=True, max_length=200, verbose_name='Vérifié par')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('checklist', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='checklist.checklist')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical check item',
                'verbose_name_plural': 'historical check items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
