# Generated by Django 5.0.2 on 2025-07-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_alter_checkitem_options_alter_checklist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='doc_url',
            field=models.URLField(blank=True, help_text='Lien vers un document ou une ressource externe pour cette tâche.'),
        ),
        migrations.DeleteModel(
            name='DocLink',
        ),
    ]
